baseURL = "https://example.com/"
languageCode = "en-us"
title = "Home"
theme = "personal-web"
copyright=" "
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "MARCO PIÑA :pineapple:"
  sub = "Research Economist"

[params.main]
  latestPublishHeader = " "

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday] 
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404
  rendererSafe = false # set to true if wish to remove the unsafe renderer setting below (recommended). Titles will not be run through markdownify

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"
  
[params.sidebar]
  backgroundImage = 'images/WP.png' # header background image - default "/images/default_sidebar.jpg" images/side_bar.jpg
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = 'images/UVA.jpeg' # - default "/images/edna-west.jpg" images/mp.jpg
[params.assets]
  favicon = ""
  customCSS = ""

[params.social]
  github = "https://github.com/marco-pina/Utilities"
  twitter = ""
  linkedin = "https://www.linkedin.com/in/marco-p-c/"

[params.contact]
  email = "wju9nq@virginia.edu"
  text= "" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "resume"
  name = "[Resume]"
  title = "Resume"
  url = "https://docs.google.com/gview?url=https://github.com/marco-pina/resume/raw/main/marcopinaCV.pdf&embedded=true"
  weight = -120

[[menu.main]]
  identifier = "papers"
  name = "Published Papers"
  title = "Published Papers"
  url = "/Published Papers/"
  weight = -110

[[menu.main]]
  identifier = "working papers"
  name = "Working Papers"
  title = "Working Papers"
  url = "/Working Papers/"
  weight = -100  

[[menu.main]]
  identifier = "codes"
  name = "Public Codes"
  title = "Public Codes"
  url = "/Public Codes/"
  weight = -90

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true